### ISSUE TITLE
Flutter Loading material icons not working 

### ISSUE THREAD

**Issue by Tickaren** [bridgedxyz/dynamic#10]
**Describe the bug**
Loading material icons from string value does not work

**To Reproduce**
`XIcon(new XIconData("material://icons.directions_run")),`

**Expected behavior**
Rendering the icon

**Screenshots**
**Desktop (please complete the following information):**
 - OS: n/a
 - Browser n/a
 - Version n/a

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Version all

**Additional context**
I can get it to work with:
`XIcon(new XIconData.fromMaterialIconName("directions_run"))`
But some icons will be needed to be rendered by url and some from material icons..

**Comment by softmarshmallow** [comment]
@Tickaren can I help you? or did you managed to do it
