### ISSUE TITLE
Sound null safety

### ISSUE THREAD

**Issue by psrcek** [bridgedxyz/dynamic#14]
**Is your feature request related to a problem? Please describe.**
The package currently doesn't support sound null safety. Flutter 2.0.0 requires that.

**Describe the solution you'd like**
I want support since I cannot update my own packages until then.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
![image](https://user-images.githubusercontent.com/13370323/110448254-4e8f7500-80c1-11eb-9538-08ea9285bf0c.png)

https://dart.dev/null-safety/migration-guide

**Comment by softmarshmallow** [comment]
Thanks for the report. our team can work on this.
It may take up to few days to weeks. How urgent is your case?

p.s. will update on this thread when our team diggs on it. Meanwhile feel free to make a PR for the fix.

**Comment by psrcek** [comment]
Considering this is required in the new dart SDK and flutter >= 2.0.0 you should probably get working on this soon :smile: 
It literally makes your package impossible to use. I was expecting this simple of a package to be updated within a month. Do you still plan on updating this or will we have to start rolling our own solution?

**Comment by softmarshmallow** [comment]
Thanks for reminding me. I'll work on this asap. but since i have so much on my table, I really would appreciate your contribution to it if possible. Will there be a chance for that?

**Comment by psrcek** [comment]
Alright, this is literally the only package now that prevents about half of our apps from being migrated, I guess you aren't serious at all about updating this or maintaining it. I am forced now to switch to an alternative and seeing the state of this project I guess that's for the better.

**Comment by softmarshmallow** [comment]
I'll work on it today. Not sure how long it would take. may be max 10 hours?

**Comment by softmarshmallow** [comment]
available on pub.dev
