### ISSUE TITLE
Loading icons from remote URL does not work

### ISSUE THREAD

**Issue by alhafoudh** [bridgedxyz/dynamic#9]
**Describe the bug**
Loading icons from remote URL does not work.

**To Reproduce**
```
Icon(XIconData.fromUri("https://example.com/icon.svg"))
```

**Expected behavior**
Render remote icon

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all

**Additional context**
-

**Comment by softmarshmallow** [comment]
```dart
XIcon(XIconData.fromUri(
              "https://raw.githubusercontent.com/bridgedxyz/dynamic/master/flutter/packages/x_icon/doc/remote-icon-example/twotone_brightness_auto_black_18dp.png"));
```


here is the working example. 

more example can be found from [here](https://github.com/bridgedxyz/dynamic/blob/master/flutter/packages/x_icon/example/lib/main.dart)

-----
https://github.com/bridgedxyz/dynamic/blob/master/flutter/packages/x_icon/example/lib/main.dart

**Comment by softmarshmallow** [comment]
![image](https://user-images.githubusercontent.com/16307013/93669324-6bfa6380-face-11ea-9b4a-1936f25050ec.png)

**Comment by alhafoudh** [comment]
It looks that when I use `flutter_remote_icon` package it does not work, I will try with `x_icon`

**Comment by softmarshmallow** [comment]
@alhafoudh  Yes, the flutter_remote_icon is not updated, we migrated the same functionality to x_icon, and will be updated on x_icon
